label: ${stats.label}/${find.rmin}_${find.rmax}_${find.rnum}
outfile:
  - ${find.label}/find.npz
rmin: ${radius.rmin}
rmax: ${radius.rmax}
rnum: ${radius.rnum}
batch:
  - ${env.num_devices}
  - 100
force: ${force}
