dynamics:
  type: double_exp
  tau1: 0.08
  tau2: 0.16
  duration: 1.0
  hz: ${data.imgs.hz}
penalty:
  la:
    type: MaxNormNonNegativeL1
    factor: 20.0
  lu:
    type: MaxNormNonNegativeL1
    factor: 20.0
  lb: 0.1
  bs: 0.1
  bt: 0.1
clean:
  radius: ${init.find.radius}
  reduce:
    min_radius: ${init.reduce.min_radius}
    max_radius: ${init.reduce.max_radius}
    min_distance_ratio: 0.0
    max_udense: 0.15
    min_bsparse: 10.0
