label: ""
dynamics:
  type: double_exp
  tau1: 0.08
  tau2: 0.16
  duration: 1.0
  hz: ${data.imgs.hz}
penalty:
  la:
    type: MaxNormNonNegativeL1
    factor: 0.0
  lu:
    type: MaxNormNonNegativeL1
    factor: 0.0
  lb: 0.0
  bs: 0.0
  bt: 0.0
