[project]
name = "hotaru"
description = "High performance Optimizer to extract spike Timing And cell location from calcium imaging data via lineaR impUlse"
readme = 'README.md'
keywords = [
    "Calcium Imaging",
    "Spike Detection",
    "Cell Extraction",
]
repository = "https://github.com/tk2lab/HOTARU"

authors = [
    { name = "TAKEKAWA Takashi", email = "takekawa@tk2lab.org" },
]
license = "GPL-3.0-only"

dynamic = ["version"]
requires-python = ">=3.14"

dependencies = [
    # core
    "keras",
    "jax[cuda12]; sys_platform == 'linux'",
    "jax; sys_platform != 'linux'",
    # input
    "tifffile",
    "zarr",
    "h5py>=3.16",
    # output
    "polars",
    "holoviews[recommended]",
    "hvplot",
    "seaborn",
    "av",
    # UI
    "hydra-core",
    "tqdm",
]

[project.scripts]
hotaru = "hotaru.__main__:main"
version = "versioningit:get_version"

[dependency-groups]
dev = [
    "torch",
    "versioningit",
    "ruff>=0.15.12",
    "ty>=0.0.34",
    "ipython",
    "pytest",
    "marimo",
    "jupyterlab>=4.5.7",
]
benchmark = [
    "caiman",
    "suite2p[all]>=1.0.0.1",
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit]
next-version = "smallest-release"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{next_version}+d{build_date:%Y%m%d%H%M}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}-d{build_date:%Y%m%d%H%M}"

[tool.uv.pip]
only-binary = [":all:"]

[tool.uv.sources]
torch = [
    { index = "pypi", marker = "sys_platform == 'darwin'" },
    { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]
caiman = { git = "https://github.com/flatironinstitute/caiman" }

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

[[tool.uv.index]]
name = 'pytorch-cu128'
url = 'https://download.pytorch.org/whl/cu128'
explicit = true

[tool.pytest.ini_options]
filterwarnings = [
    'ignore::DeprecationWarning:keras',
]
