[project]
name = "hotaru"
description = "High performance Optimizer to extract spike Timing And cell location from calcium imaging data via lineaR impUlse"
readme = 'README.md'
keywords = [
    "Calcium Imaging",
    "Spike Detection",
    "Cell Extraction",
]
repository = "https://github.com/tk2lab/HOTARU"

authors = [
    { name = "TAKEKAWA Takashi", email = "takekawa@tk2lab.org" },
]
license = "GPL-3.0-only"

dynamic = ["version"]
requires-python = ">=3.14"

dependencies = [
    # core
    "keras",
    # input
    "tifffile>=2022.8",
    "zarr>=3.2.1",
    # output
    "polars>=1.40.1",
    "hvplot",
    "seaborn",
    "av>=10.0",
    # UI
    "hydra-core>=1.3",
    "tqdm>=4.64",
]

[project.optional-dependencies]
jax = [
    "jax; sys_platform != 'linux'",
    "jax[cuda12]; sys_platform == 'linux'",
]
torch = [
    "torch",
]

[project.scripts]
version = "versioningit:get_version"
hotaru = "hotaru.__main__:main"

[dependency-groups]
dev = [
    "versioningit",
    "ruff>=0.15.12",
    "ty>=0.0.34",
    "ipython",
    "pytest>=9.0.3",
    "marimo>=0.23.5",
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit]
next-version = "smallest-release"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{next_version}+d{build_date:%Y%m%d%H%M}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}-d{build_date:%Y%m%d%H%M}"

[tool.uv]
environments = [
#    "sys_platform == 'linux'",
#    "sys_platform == 'darwin'",
]

[tool.uv.sources]
torch = [
    { index = "pypi", marker = "sys_platform == 'darwin'" },
    { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

[[tool.uv.index]]
name = 'pytorch-cu128'
url = 'https://download.pytorch.org/whl/cu128'
explicit = true
