label: ${init.radius.type}${init.radius.num}-${init.radius.min}-${init.reduce.min_radius}-${init.reduce.max_radius}-${init.radius.max}-${init.reduce.min_distance_ratio}
radius:
  type: logscale
  min: 2
  max: 12
  num: 16
reduce:
  min_radius: 2.8
  max_radius: 11.0
  min_distance_ratio: 1.8
