find:
  outfile: find.npz
  rmin: ${radius.rmin}
  rmax: ${radius.rmax}
  rnum: ${radius.rnum}
  batch:
    - ${env.num_devices}
    - 100
  force: false
reduce:
  outfile: reduce.cvs
  rmin: ${radius.rmin2}
  rmax: ${radius.rmax2}
  thr: ${radius.thr}
  block_size: 100
  force: false
segment:
  outfile: footprint00.npy
  batch:
    - ${env.num_devices}
    - 100
  force: false
temporal:
  outfile: 00spike.npy
  lu: 0.0
  la: 0.0
  bt: ${penalty.bt}
  bx: ${penalty.bx}
  lr: 1.0
  scale: 20
  reset: 100
  n_iter: 1000
  batch:
    - ${env.num_devices}
    - 100
  force: false
