label: ${find.label}/${reduce.rmin}_${reduce.rmax}_${reduce.thr}
outfile: ${reduce.label}/0_0reduce.csv
rmin: ${radius.rmin2}
rmax: ${radius.rmax2}
thr: ${radius.thr}
block_size: 100
loop: false
force: ${force}
