label: ${reduce.label}
outfile: ${clean.label}/${stage}_1footprint.npy
rmin: ${radius.rmin}
rmax: ${radius.rmax}
rnum: ${radius.rnum}
batch:
  - ${env.num_devices}
  - 100
loop: false
force: false
done: -1
