label: ${reduce.label}
outfile: ${clean.label}/${stage}_2footprint.npy
rmin: ${radius.rmin}
rmax: ${radius.rmax}
rnum: ${radius.rnum}
batch:
  - ${env.num_devices}
  - 100
force: ${force}
done: ${done}
