label: ${make.label}/${spatial.penalty.la}_${spatial.penalty.lu}_${spatial.penalty.bx}_${spatial.penalty.bt}
penalty:
  la: ${penalty.la}
  lu: ${penalty.lu}
  bx: ${penalty.bx}
  bt: ${penalty.bt}
prepare:
  outfile: ${spatial.label}/${stage}_0prepare.npz
  batch:
    - ${env.num_devices}
    - 1000
  force: ${spatial.force}
  done: ${spatial.done}
optimize:
  outfile: ${spatial.label}/${stage}_1spatial.npy
  lr: 0.005
  scale: 20.0
  n_epoch: 100
  n_step: 100
  early_stop:
    tol: 1e-5
  loss:
    num_devices: ${env.num_devices}
  prox:
    num_devices: ${env.num_devices}
  force: ${spatial.force}
  done: ${spatial.done}
force: ${force}
done: ${done}
