defaults:
  - data: sample
  - radius: default
  - dynamics: default
  - penalty: default
  - stats: default
  - find: default
  - reduce: default
  - segment: default
  - spatial: default
  - clean: default
  - temporal: default
  - _self_

outdir: ${data.dir}
n_iter: 2
stage:

env:
  num_devices:

server:
  port: 8888
  debug: true

hydra:
  job_logging:
    root:
      level: WARNING
