defaults:
  - _self_
  - data: nomask20
  - radius: log_2_16
  - density: min2
  - dynamics: double_exp_0.08_0.16
  - penalty: 20_30_0.1_0.1
  - init
  - train
  - hotaru

thr_distance: 2
max_train_step: 10
batch_frame: 100
block_size: 100

num_devices: 1
force: false

hydra:
  job:
    name: hotaru
  searchpath: 
    - file://.
  job_logging:
    formatters:
      brief:
        format: '%(message)s'
    handlers:
      hotaru:
        class: hotaru.utils.LoggingHandler
        level: INFO
        formatter: brief
        stream: ext://sys.stdout
    root:
      handlers:
      - file
      - hotaru
