defaults:
  - data: sample 
  - radius: default
  - dynamics: default
  - penalty: default
  - stats: default
  - init: default
  - body: default
  - _self_

n_iter: 1

env:
  num_devices:

hydra:
  job_logging:
    root:
      level: WARNING
  mode: MULTIRUN
  sweeper:
    params:
      stage: range(${n_iter})

stage: 0
next: ${stage} + 1
