defaults:
  - _self_
  - hydra/local
  - hotaru: default

bg_type: bg
fix_top: true

mode: run
max_train_step: 10
early_stop: true
force_from:
  - 100
  - spatial
trace: false

gui:
  server:
    host: localhost
    port: 8080
  browser:
    open: true

hydra:
  searchpath:
    - file://
  output_subdir: hydra
  job:
    name: hotaru
    env_set:
      TF_CPP_MIN_LOG_LEVEL: 2
      #TF_CPP_VMODULE: bfc_allocator=1
      #JAX_PLATFORMS: cuda
      #JLA_PYTHON_CLIENT_PREALLOCATE: true
