defaults:
  - _self_
  - data: default
  - radius: default
  - init: default
  - model: default
  - cmd: default
  - outputs: default
  - env: default
  - hydra/local
  - hotaru

mode: test

max_train_step: 10
early_stop: true
force_from:
  - 100
  - spatial
trace: false

plot:
  stage: ${max_train_step}
  time: null
  seg_max:
    base: 0.5
    plot_bg: false

gui:
  server:
    host: localhost
    port: 8080
  browser:
    open: true

hydra:
  searchpath:
    - file://
  job:
    name: hotaru
    env_set:
      TF_CPP_MIN_LOG_LEVEL: 2
      #TF_CPP_VMODULE: bfc_allocator=1
      #JAX_PLATFORMS: cuda
      #JLA_PYTHON_CLIENT_PREALLOCATE: true
