defaults:
  - data: default
  - radius: default
  - dynamics: default
  - penalty: default
  - stats: default
  - find: default
  - reduce: default
  - make: default
  - spatial: default
  - clean: default
  - temporal: default
  - _self_

srcdir: .
outdir: ${data.dir}
stage: 9
force: false
done: null

env:
  num_devices: 1

server:
  host: 127.0.0.1
  port: 8888
  debug: true
  open_browser: true

hydra:
  run:
    dir: ${outdir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    root:
      level: WARNING
