defaults:
  - _self_
  - data: default
  - radius: default
  - density: default
  - model: default
  - cmd: default
  - outputs: default
  - gpu: default
  - hydra/local
  - hotaru

max_train_step: 10
early_stop: true
force_from:
  - 100
  - spatial
trace: false

gui:
  use: false
  server:
    host: localhost
    port: 8080
  browser:
    open: true

hydra:
  searchpath:
    - file://
  job:
    name: hotaru
    env_set:
      TF_CPP_MIN_LOG_LEVEL: 1
      JAX_PLATFORMS: cuda
