lable: current
outfile: spike${temporal.label}.npy
lu: ${penalty.lu}
la: ${penalty.la}
bt: ${penalty.bt}
bx: ${penalty.bx}
lr: 1.0
scale: 20
reset: 100
n_iter: 1000
batch:
  - ${env.num_devices}
  - 100
force: false
