label: ${make.label}/${temporal.penalty.la}_${temporal.penalty.lu}_${temporal.penalty.bx}_${temporal.penalty.bt}
penalty:
  la: ${penalty.la}
  lu: ${penalty.lu}
  bx: ${penalty.bx}
  bt: ${penalty.bt}
prepare:
  outfile: ${temporal.label}/${stage}_3prepare.npz
  batch:
    - ${env.num_devices}
    - 100
  force: ${temporal.force}
  done: ${temporal.done}
optimize:
  outfile: ${temporal.label}/${stage}_4spike.npy
  lr: 0.005
  scale: 20
  n_epoch: 100
  n_step: 100
  early_stop:
    tol: 1e-5
  loss:
    num_devices: ${env.num_devices}
  prox:
    num_devices: ${env.num_devices}
  force: ${temporal.force}
  done: ${temporal.done}
force: ${force}
done: ${done}
