label: ${reduce.label}
outfile: ${temporal.label}/${stage}_2spike.npy
batch:
  - ${env.num_devices}
  - 100
lr: 100.0
scale: 20
n_epoch: 100
n_step: 100
early_stop:
  tol: 1e-5
force: ${force}
done: ${done}
