plot:
  name: Kd32
  final: 15
  time: null

max_train_step: 20
data:
  imgs:
    file: Kd32.tif
    width: 720
radius:
  type: logscale
  num: 16
  min: 2
  max: 13
init:
  remove_find: false
  remove_reduce: false
  reduce:
    min_radius: 3.0
    max_radius: 11.0
    min_distance_ratio: 2.0
model:
  penalty:
    la:
      type: MaxNormNonNegativeL1
      factor: 20.0
    lu:
      type: MaxNormNonNegativeL1
      factor: 30.0
  clean:
    reduce:
      min_distance_ratio: 0.0
      max_udense: 0.15
      min_bsparse: 10.0
cmd:
  label: div22
  clip:
    type: Div
    ynum: 2
    xnum: 2
    margin: 50
