# @package _global_

defaults:
  - data: default
  - radius: default
  - dynamics: default
  - penalty: default
  - init: default
  - clean: default
  - cmd: default
  - env: default
  - outputs: default
