stats:
  factor: 1000.0
  prefetch: 1
find:
  factor: 1000.0
  prefetch: 1
reduce:
  block_size: 100
make:
  factor: 1000.0
  prefetch: 1
clean:
  factor: 1000.0
  prefetch: 1
spatial:
  clip:
    - null
  prepare:
    factor: 1.0
    prefetch: 1
  optimize:
    lr: 1e-2
    nesterov_scale: 20
  step:
    n_epoch: 100
    n_step: 100
    tol: 1e-3
    patience: 10
temporal:
  prepare:
    factor: 1.0
    prefetch: 1
  optimize:
    lr: 1e-3
    nesterov_scale: 20
  step:
    n_epoch: 100
    n_step: 100
    tol: 1e-5
    patience: 10
