stats:
  factor: 1000.0
  prefetch: 1
find:
  factor: 1000.0
  prefetch: 1
reduce:
  block_size: 100
make:
  factor: 1000.0
  prefetch: 1
clean:
  factor: 1000.0
  prefetch: 1
spatial:
  clip:
    type: Div
    ynum: 1
    xnum: 1
    margin: 0
  prepare:
    factor: 10.0
    prefetch: 1
  optimize:
    lr: 0.01
    nesterov_scale: 20
  step:
    max_epoch: 1000
    steps_par_epoch: 100
    tol: 1e-5
    patience: 10
temporal:
  prepare:
    factor: 10.0
    prefetch: 1
  optimize:
    lr: 0.01
    nesterov_scale: 20
  step:
    max_epoch: 1000
    steps_par_epoch: 100
    tol: 1e-5
    patience: 10
