stats:
  factor: 1000.0
  prefetch: 1
find:
  factor: 1000.0
  prefetch: 1
reduce:
  block_size: 100
make:
  factor: 1000.0
  prefetch: 1
clean:
  factor: 1000.0
  prefetch: 1
spatial:
  clip:
    type: Div
    ynum: 1
    xnum: 1
    margin: 0
  prepare:
    factor: 10.0
    prefetch: 1
  step:
    lr: 0.01
    nesterov: 20
    max_epoch: 100
    steps_par_epoch: 100
    tol: 1e-5
    patience: 3
temporal:
  clip:
    type: Div
    ynum: 1
    xnum: 1
    margin: 0
  prepare:
    factor: 10.0
    prefetch: 1
  step:
    lr: 0.01
    nesterov: 20
    max_epoch: 100
    steps_par_epoch: 100
    tol: 1e-5
    patience: 3
