stats:
  factor: 500.0
find:
  factor: 500.0
reduce:
  block_size: 100
make:
  factor: 1000.0
clean:
  factor: 1000.0
spatial:
  prepare:
    factor: 1.0
    prefetch: 1
  optimize:
    lr: 0.005
    scale: 20
  step:
    n_epoch: 100
    n_step: 100
    tol: 1e-5
temporal:
  prepare:
    factor: 1.0
    prefetch: 1
  optimize:
    lr: 0.005
    scale: 20
  step:
    n_epoch: 100
    n_step: 100
    tol: 1e-5
