label: default
stats:
  env: ${env}
  factor: 1000.0
  prefetch: 1
find:
  env: ${env}
  factor: 1000.0
  prefetch: 1
reduce:
  block_size: 100
make:
  env: ${env}
  factor: 1000.0
  prefetch: 1
clean:
  env: ${env}
  factor: 1000.0
  prefetch: 1
clip:
  type: Div
  ynum: 1
  xnum: 1
  margin: 0
spatial:
  clip: ${cmd.clip}
  prepare:
    env: ${env}
    factor: 10.0
    prefetch: 1
  step:
    env: ${env}
    lr: 1e-8
    nesterov: 20
    max_epoch: 1000
    steps_par_epoch: 100
    tol: 1e-4
    patience: 3
temporal:
  clip: ${cmd.clip}
  prepare:
    env: ${env}
    factor: 10.0
    prefetch: 1
  step:
    env: ${env}
    lr: 1e-8
    nesterov: 20
    max_epoch: 1000
    steps_par_epoch: 100
    tol: 1e-4
    patience: 3
